"""
Luframe Agent Schemas

This module contains Pydantic models and enums for data validation and serialization.
"""

from .insights import Insight, InsightType, INSIGHT_ICONS
from .documents import (
    DocumentStatus,
    BoundingBox,
    TextSpan,
    DocumentPage,
    DocumentSegment,
    UploadedDocument,
    DocumentReference,
    RetrievalCandidate,
    MAX_DOCUMENTS_PER_ROOM,
    MAX_SEGMENTS_PER_DOCUMENT,
    MAX_SEGMENT_LENGTH,
    DOCUMENT_TTL_HOURS,
    DEDUPE_TTL_MINUTES,
    MIN_SEGMENT_WORDS,
    MIN_SEGMENT_DURATION,
    RRF_K,
)
from .agenda import (
    AgendaItemStatus,
    AgendaStatus,
    AgendaEventType,
    AgendaItem,
    Agenda,
    AgendaProgressEvent,
    TopicStartedEvent,
    TopicCompletedEvent,
    TopicSkippedEvent,
    MeetingStartedEvent,
    MeetingEndedEvent,
    AgendaSyncEvent,
    AgendaStateAttribute,
    StabilityState,
    TopicDetectionResult,
    AGENDA_TOPIC,
    AGENT_IDENTITY_PREFIX,
    # Trust-based LLM architecture - minimal constants for performance only
    MIN_ANALYSIS_INTERVAL,
    ANALYSIS_DEBOUNCE_SECONDS,
    MAX_TRANSCRIPT_BUFFER,
    MIN_SEGMENT_WORDS_FOR_DETECTION,
    extract_keywords,
)
from .actions import (
    ActionType,
    UrgencyLevel,
    ActionMetadata,
    ClassifiedAction,
    EMAIL_ACTION_TYPES,
    MIN_CLASSIFICATION_CONFIDENCE,
    CLASSIFICATION_TIMEOUT_SECONDS,
    MAX_CONTEXT_TURNS,
    ACTION_TYPE_PATTERNS,
    ACTION_TYPE_ICONS,
)
from .email_draft import (
    DraftStatus,
    EmailRecipient,
    MeetingContext,
    EmailDraft,
    DRAFT_GENERATION_TIMEOUT_SECONDS,
    DRAFT_GENERATION_MAX_RETRIES,
    MIN_DRAFT_CONFIDENCE,
    MAX_TRANSCRIPT_CONTEXT_TURNS,
    MAX_TRANSCRIPT_CONTEXT_CHARS,
    MAX_CONCURRENT_GENERATIONS,
    GENERATION_DEBOUNCE_SECONDS,
)

__all__ = [
    # Insights
    "Insight",
    "InsightType",
    "INSIGHT_ICONS",
    # Documents
    "DocumentStatus",
    "BoundingBox",
    "TextSpan",
    "DocumentPage",
    "DocumentSegment",
    "UploadedDocument",
    "DocumentReference",
    "RetrievalCandidate",
    "MAX_DOCUMENTS_PER_ROOM",
    "MAX_SEGMENTS_PER_DOCUMENT",
    "MAX_SEGMENT_LENGTH",
    "DOCUMENT_TTL_HOURS",
    "DEDUPE_TTL_MINUTES",
    # Hybrid retrieval constants
    "MIN_SEGMENT_WORDS",
    "MIN_SEGMENT_DURATION",
    "RRF_K",
    # Agenda (Phase 4)
    "AgendaItemStatus",
    "AgendaStatus",
    "AgendaEventType",
    "AgendaItem",
    "Agenda",
    "AgendaProgressEvent",
    "TopicStartedEvent",
    "TopicCompletedEvent",
    "TopicSkippedEvent",
    "MeetingStartedEvent",
    "MeetingEndedEvent",
    "AgendaSyncEvent",
    "AgendaStateAttribute",
    "StabilityState",
    "TopicDetectionResult",
    "AGENDA_TOPIC",
    "AGENT_IDENTITY_PREFIX",
    # Trust-based LLM architecture - minimal constants for performance only
    "MIN_ANALYSIS_INTERVAL",
    "ANALYSIS_DEBOUNCE_SECONDS",
    "MAX_TRANSCRIPT_BUFFER",
    "MIN_SEGMENT_WORDS_FOR_DETECTION",
    "extract_keywords",
    # Actions (Phase 1 of Real-Time Actions)
    "ActionType",
    "UrgencyLevel",
    "ActionMetadata",
    "ClassifiedAction",
    "EMAIL_ACTION_TYPES",
    "MIN_CLASSIFICATION_CONFIDENCE",
    "CLASSIFICATION_TIMEOUT_SECONDS",
    "MAX_CONTEXT_TURNS",
    "ACTION_TYPE_PATTERNS",
    "ACTION_TYPE_ICONS",
    # Email Drafts (Phase 3 of Real-Time Actions)
    "DraftStatus",
    "EmailRecipient",
    "MeetingContext",
    "EmailDraft",
    "DRAFT_GENERATION_TIMEOUT_SECONDS",
    "DRAFT_GENERATION_MAX_RETRIES",
    "MIN_DRAFT_CONFIDENCE",
    "MAX_TRANSCRIPT_CONTEXT_TURNS",
    "MAX_TRANSCRIPT_CONTEXT_CHARS",
    "MAX_CONCURRENT_GENERATIONS",
    "GENERATION_DEBOUNCE_SECONDS",
]
