"""
Email Draft Schemas for Hedwiq Agent

Defines the data models for email draft generation feature (Phase 3 of Real-Time Actions).
Email drafts are generated from classified email-type actions during meetings.

Key Features:
- EmailDraft model for AI-generated email drafts
- MeetingContext for contextual information
- Status tracking for draft lifecycle
"""

from enum import Enum
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field, field_validator, ConfigDict
import time
import uuid


def get_timestamp_ms() -> int:
    """Get current timestamp in milliseconds."""
    return int(time.time() * 1000)


def generate_draft_id() -> str:
    """Generate unique draft ID."""
    return f"draft-{uuid.uuid4().hex[:12]}"


class DraftStatus(str, Enum):
    """
    Status of an email draft in its lifecycle.

    Flow: generating -> ready -> (sent | rejected | edited)
    """
    GENERATING = "generating"  # Draft is being generated by LLM
    READY = "ready"            # Draft is ready for user review
    EDITED = "edited"          # User has edited the draft
    SENT = "sent"              # Email has been sent
    REJECTED = "rejected"      # User rejected the draft
    FAILED = "failed"          # Generation failed


class EmailRecipient(BaseModel):
    """
    Suggested email recipient with optional metadata.
    """
    email: Optional[str] = Field(
        None,
        description="Email address if known (from participant list)"
    )
    name: str = Field(
        ...,
        description="Name or role of the recipient",
        max_length=200
    )
    source: str = Field(
        default="inferred",
        description="How recipient was determined: 'inferred', 'explicit', 'participant'"
    )

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "email": self.email,
            "name": self.name,
            "source": self.source,
        }


class MeetingContext(BaseModel):
    """
    Meeting context information for email generation.

    Provides relevant meeting details to help LLM generate
    contextually appropriate email drafts.
    """
    meeting_title: Optional[str] = Field(
        None,
        description="Title of the meeting",
        max_length=200
    )
    meeting_date: Optional[str] = Field(
        None,
        description="Date of the meeting (ISO format or human readable)"
    )
    participants: List[str] = Field(
        default_factory=list,
        description="List of participant names in the meeting"
    )
    agenda_topics: List[str] = Field(
        default_factory=list,
        description="Agenda topics being discussed"
    )
    room_id: Optional[str] = Field(
        None,
        description="Room identifier for meeting links"
    )

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "meetingTitle": self.meeting_title,
            "meetingDate": self.meeting_date,
            "participants": self.participants,
            "agendaTopics": self.agenda_topics,
            "roomId": self.room_id,
        }


class EmailDraft(BaseModel):
    """
    An AI-generated email draft from a meeting action item.

    This model represents a complete email draft ready for user review.
    Generated when ActionClassifier identifies an email-type action.

    Published to the hedwiq.email_draft topic for frontend consumption.
    """

    id: str = Field(default_factory=generate_draft_id)

    # Link to source action
    action_id: str = Field(
        ...,
        description="ID of the ClassifiedAction that triggered this draft"
    )
    original_insight_id: str = Field(
        ...,
        description="ID of the original action_item insight"
    )

    # Email content
    suggested_to: List[EmailRecipient] = Field(
        default_factory=list,
        description="Suggested email recipients"
    )
    subject: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Email subject line"
    )
    body: str = Field(
        ...,
        min_length=10,
        max_length=5000,
        description="Email body content"
    )

    # Context that generated this draft
    meeting_context: MeetingContext = Field(
        default_factory=MeetingContext,
        description="Meeting context used for generation"
    )
    transcript_context: Optional[str] = Field(
        None,
        max_length=2000,
        description="Transcript excerpt used for generation"
    )

    # Source action data (copied for convenience)
    action_content: str = Field(
        ...,
        description="Original action item content"
    )
    action_type: str = Field(
        ...,
        description="Type of email action (email_followup, email_share, email_schedule)"
    )
    speaker_name: Optional[str] = Field(
        None,
        description="Name of person who mentioned the action"
    )

    # Draft metadata
    status: DraftStatus = Field(
        default=DraftStatus.READY,
        description="Current status of the draft"
    )
    generation_confidence: float = Field(
        default=0.8,
        ge=0.0,
        le=1.0,
        description="Confidence in draft quality"
    )

    # Timestamps
    generated_at: int = Field(
        default_factory=get_timestamp_ms,
        description="When the draft was generated (ms)"
    )

    # Error tracking (for failed status)
    error_message: Optional[str] = Field(
        None,
        description="Error message if generation failed"
    )

    @field_validator("subject")
    @classmethod
    def validate_subject(cls, v: str) -> str:
        """Ensure subject is not just whitespace."""
        if not v.strip():
            raise ValueError("Subject cannot be empty")
        return v.strip()

    @field_validator("body")
    @classmethod
    def validate_body(cls, v: str) -> str:
        """Ensure body has meaningful content."""
        if len(v.split()) < 5:
            raise ValueError("Body must have at least 5 words")
        return v

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization (camelCase for frontend)."""
        # Handle enum values
        status_value = (
            self.status.value
            if hasattr(self.status, 'value')
            else self.status
        )

        return {
            "id": self.id,
            "actionId": self.action_id,
            "originalInsightId": self.original_insight_id,
            "suggestedTo": [r.to_dict() for r in self.suggested_to],
            "subject": self.subject,
            "body": self.body,
            "meetingContext": self.meeting_context.to_dict(),
            "transcriptContext": self.transcript_context,
            "actionContent": self.action_content,
            "actionType": self.action_type,
            "speakerName": self.speaker_name,
            "status": status_value,
            "generationConfidence": self.generation_confidence,
            "generatedAt": self.generated_at,
            "errorMessage": self.error_message,
        }

    # Pydantic v2 configuration
    model_config = ConfigDict(use_enum_values=True)


# Generation constants
DRAFT_GENERATION_TIMEOUT_SECONDS = 5.0   # Max time for LLM draft generation
DRAFT_GENERATION_MAX_RETRIES = 1         # Retries on timeout/error
MIN_DRAFT_CONFIDENCE = 0.6               # Minimum confidence to publish draft

# Context constants
MAX_TRANSCRIPT_CONTEXT_TURNS = 10        # Number of transcript turns to include
MAX_TRANSCRIPT_CONTEXT_CHARS = 1500      # Max chars for transcript context

# Rate limiting
MAX_CONCURRENT_GENERATIONS = 3           # Backpressure limit
GENERATION_DEBOUNCE_SECONDS = 0.5        # Debounce for nearby actions
